   - name: �� Sync files
     uses: SamKirkland/FTP-Deploy-Action@4.0.0
     with:
       server: ${{ secrets.FTP_SERVER }}  # <-- ESTE É O PARÂMETRO QUE ESTÁ FALTANDO!
       username: ${{ secrets.FTP_USERNAME }}
       password: ${{ secrets.FTP_PASSWORD }}
       local-dir: C:\xampp\htdocs\drones # Caminho local dos arquivos a serem enviados
       server-dir: /caminho/no/servidor/      # Caminho no servidor FTP
